clear all

file_name = 'StroicizamFINAL.xlsx';

[Vload, MaxDepth, velocityMaxSpeed, kmMaxRange,...
CombTempFlagRange, TurbTempFlagRange, SaturatedFlagRange, deadFlagRange, evapErosionFlagRange, evapSuperFlagRange, pumpSpeedExceedFlagRange,...
CombTempFlagSpeed, TurbTempFlagSpeed, SaturatedFlagSpeed, deadFlagSpeed, evapErosionFlagSpeed, evapSuperFlagSpeed, pumpSpeedExceedFlagSpeed,...
CombTempFlagDepth, TurbTempFlagDepth, SaturatedFlagDepth, deadFlagDepth, evapErosionFlagDepth, evapSuperFlagDepth, pumpSpeedExceedFlagDepth, flag_MAX_DEPT_minPower] =...
SolutionEval(file_name)

rezultati = table(velocityMaxSpeed, kmMaxRange, MaxDepth, Vload,...
    CombTempFlagSpeed, TurbTempFlagSpeed, SaturatedFlagSpeed, deadFlagSpeed, evapErosionFlagSpeed, evapSuperFlagSpeed, pumpSpeedExceedFlagSpeed,...
    CombTempFlagRange, TurbTempFlagRange, SaturatedFlagRange, deadFlagRange, evapErosionFlagRange, evapSuperFlagRange, pumpSpeedExceedFlagRange,...
    CombTempFlagDepth, TurbTempFlagDepth, SaturatedFlagDepth, deadFlagDepth, evapErosionFlagDepth, evapSuperFlagDepth, pumpSpeedExceedFlagDepth, flag_MAX_DEPT_minPower);